# Generated by Django 2.2 on 2020-04-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HedgeFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cik', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
