# Generated by Django 2.2 on 2020-04-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip', models.TextField()),
                ('value', models.IntegerField()),
                ('name_of_issuer', models.TextField()),
                ('title_of_class', models.TextField()),
                ('number_of_shares', models.IntegerField()),
                ('investment_discretion', models.TextField()),
                ('sh', models.TextField()),
                ('voting_authority_sole', models.IntegerField()),
                ('voting_authority_shared', models.IntegerField()),
                ('voting_authority_none', models.IntegerField()),
                ('report_date', models.DateField()),
                ('hedge_fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.HedgeFund')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Security')),
            ],
        ),
    ]
