# Generated by Django 2.2 on 2020-04-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_filing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip', models.TextField()),
                ('ticker', models.TextField()),
            ],
        ),
    ]
