# Generated by Django 2.2 on 2020-04-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tickermap'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgefund',
            name='strategy',
            field=models.TextField(default='Not Available'),
            preserve_default=False,
        ),
    ]
