# Generated by Django 2.2 on 2020-04-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hedgefund_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickermap',
            name='as_of_date',
            field=models.DateField(null=True),
        ),
    ]
